let avgCycleLen = 28;

/* ─── symptom list ─────────────────────────────────────── */
const SYM_CATS = {
    'Fysiek': [
        'Krampen',
        'Buikpijn',
        'Rugpijn',
        'Hoofdpijn',
        'Misselijkheid',
        'Diarree',
        'Constipatie',
        'Fysieke vermoeidheid',
        'Opgeblazen gevoel',
        'Gevoelige borsten',
        'Cravings',
        'Verhoogde eetlust',
        'Verhoogde energie',
        'Verhoogd libido',
        'Heldere huid',
        'Mittelschmerz',
    ],
    'Mentaal & emotioneel': [
        'Mentale vermoeidheid',
        'Stemmingswisselingen',
        'Prikkelbaarheid',
        'Angst',
        'Onrust',
        'Somberheid',
        'Onzekerheid',
        'Piekeren',
        'Slaapproblemen',
        'Concentratieproblemen',
    ],
};
const ALL_SYMPTOMS = Object.values(SYM_CATS).flat();
const SYM_CAT_COLORS = {
    'Fysiek':               '#c88448',
    'Mentaal & emotioneel': '#c88448',
};

/* ─── phase data ───────────────────────────────────────── */
const PHASES = [
    {
        range: [1, 5], name: 'Menstruatiefase', days: 'Dag 1–5', color: '#c0304a',
        description: 'Het baarmoederslijmvlies stoot af omdat progesteron en oestradiol zijn gedaald: dat veroorzaakt het bloedverlies en de prostaglandinen die de baarmoeder laten samentrekken, wat krampen en rugpijn geeft. Het verlies van bloed en ijzer kan ook vermoeidheid versterken, vooral bij een zware menstruatie. FSH begint laag maar stijgt lichtjes tot dag 3–4 om nieuwe follikels te activeren.',
        hormones: [
            { name: 'Oestradiol',   fill: 12, label: 'laag',                color: '#e8d060' },
            { name: 'Progesteron', fill: 3,  label: 'zeer laag',           color: '#4db8c8' },
            { name: 'FSH',         fill: 30, label: 'matig', color: '#7ab55c' },
            { name: 'LH',          fill: 8,  label: 'laag',                color: '#e87ab0' },
        ],
        symptoms: ['Krampen', 'Buikpijn', 'Rugpijn', 'Fysieke vermoeidheid', 'Hoofdpijn', 'Misselijkheid', 'Diarree'],
        prevalence: { 'Krampen': 84, 'Buikpijn': 80, 'Rugpijn': 75, 'Fysieke vermoeidheid': 70, 'Hoofdpijn': 45, 'Misselijkheid': 25, 'Diarree': 20 },
        sport:   { score: 1, tip: 'Yoga, wandelen, zwemmen.' },
        sociaal: { score: 2, tip: 'Kleine kring, één-op-één. Grote verplichtingen vermijden.' },
        mentaal: { score: 3, tip: 'Een rustige fase zonder uitgesproken stemmingsklachten. Je hoofd wordt vaak weer helderder nu de PMS achter de rug is.' },
        denkvermogen: { score: 2, tip: 'Je denkt meer intuïtief dan analytisch. Goed voor reflecteren en evalueren, minder geschikt voor scherpe analyse of nieuwe leerstof.' },
        plannen: 'Je lichaam heeft rust nodig en je hoofd doet het even wat rustiger aan. Houd je agenda licht en voel je niet bezwaard als je afspraken afzegt of uitstelt.',
    },
    {
        range: [6, 9], name: 'Vroege folliculaire fase', days: 'Dag 6–9', color: '#5aaa70',
        description: 'FSH stimuleert meerdere follikels die oestradiol beginnen te produceren. De energie stijgt langzaam, het hoofd wordt helderder en de stemming verbetert.',
        hormones: [
            { name: 'Oestradiol',   fill: 47, label: 'stijgend', color: '#e8d060' },
            { name: 'Progesteron', fill: 3,  label: 'zeer laag',           color: '#4db8c8' },
            { name: 'FSH',         fill: 23, label: 'licht dalend',   color: '#7ab55c' },
            { name: 'LH',          fill: 8,  label: 'laag',           color: '#e87ab0' },
        ],
        symptoms: ['Verhoogde energie'],
        sport:   { score: 3, tip: 'Cardio opbouwen, lichte krachttraining.' },
        sociaal: { score: 3, tip: 'Ontspannen afspraken, kleinere groepen.' },
        mentaal: { score: 3, tip: 'Zelfvertrouwen keert terug. Goed moment om dingen op te pakken die je vorige week uitstelde.' },
        denkvermogen: { score: 3, tip: 'Hoofd wordt helderder en creatiever. Goed voor brainstormen en nieuwe ideeën verkennen.' },
        plannen: 'Energie en motivatie keren terug. Goed moment om nieuwe dingen op te starten die aandacht en focus vragen, of om dingen op te pakken die je de afgelopen week liet liggen.',
    },
    {
        range: [10, 12], name: 'Late folliculaire fase', days: 'Dag 10–12', color: '#3a9e72',
        description: 'Één dominant follikel produceert steeds meer oestradiol. Dit geeft een piek in energie, stemming en mentale scherpte. De meeste vrouwen voelen zich in deze periode het best.',
        hormones: [
            { name: 'Oestradiol',   fill: 75, label: 'hoog stijgend', color: '#e8d060' },
            { name: 'Progesteron', fill: 3,  label: 'zeer laag',          color: '#4db8c8' },
            { name: 'FSH',         fill: 14, label: 'laag',  color: '#7ab55c' },
            { name: 'LH',          fill: 10, label: 'laag', color: '#e87ab0' },
        ],
        symptoms: ['Verhoogde energie', 'Verhoogd libido'],
        sport:   { score: 5, tip: 'Krachttraining, intensieve cardio, HIIT.' },
        sociaal: { score: 4, tip: 'Feestjes, grote groepen, nieuwe mensen.' },
        mentaal: { score: 4, tip: 'Neem initiatieven die je al een tijdje uitstelde. Je gevoel klopt nu redelijk, vertrouw het.' },
        denkvermogen: { score: 4, tip: 'Scherpste cognitieve fase. Goed voor complexe taken en nieuwe projecten die concentratie vragen.' },
        plannen: 'Je zit in een van je sterkste weken. Plan hier de afspraken die je energie en zelfvertrouwen vragen: pitches, moeilijke gesprekken, sociale events.',
    },
    {
        range: [13, 15], name: 'Ovulatie', days: 'Dag 13–15', color: '#F0A000',
        description: 'Een plotselinge LH-piek triggert de eisprong. Het rijpe eitje verlaat de eierstok, het vruchtbaarste moment van de cyclus. Oestradiol bereikt zijn absolute piek.',
        hormones: [
            { name: 'Oestradiol',   fill: 93,  label: 'piek',           color: '#e8d060' },
            { name: 'Progesteron', fill: 8,   label: 'licht stijgend', color: '#4db8c8' },
            { name: 'FSH',         fill: 63,  label: 'piek',    color: '#7ab55c' },
            { name: 'LH',          fill: 100, label: 'piek',   color: '#e87ab0' },
        ],
        symptoms: ['Verhoogde energie', 'Verhoogd libido', 'Mittelschmerz', 'Hoofdpijn', 'Verhoogde eetlust', 'Heldere huid'],
        sport:   { score: 5, tip: 'Persoonlijke records, wedstrijden. Let op: gewrichten iets gevoeliger.' },
        sociaal: { score: 5, tip: 'Netwerken, eerste indrukken, grote sociale events.' },
        mentaal: { score: 5, tip: 'Je kunt nu veel aan, maar let op overmoedigheid.' },
        denkvermogen: { score: 5, tip: 'Verbale vloeiendheid en focus op hun best. Goed voor pitches, onderhandelen en complexe beslissingen.' },
        plannen: 'Energie en zelfvertrouwen zijn op hun hoogst. Gebruik dit voor netwerken, sollicitatiegesprekken en onderhandelen. Bedenk bij nieuwe plannen wel of ze ook realistisch zijn als je energieniveau over twee weken lager ligt.',
    },
    {
        range: [16, 20], name: 'Vroege luteale fase', days: 'Dag 16–20', color: '#3A80C0',
        description: 'Het corpus luteum produceert progesteron ter voorbereiding op mogelijke innesteling. Oestradiol heeft een tweede, kleinere piek. Energie is nog redelijk maar wordt geleidelijk rustiger.',
        hormones: [
            { name: 'Oestradiol',   fill: 44, label: 'stijgend', color: '#e8d060' },
            { name: 'Progesteron', fill: 90, label: 'flink stijgend',    color: '#4db8c8' },
            { name: 'FSH',         fill: 15, label: 'laag',    color: '#7ab55c' },
            { name: 'LH',          fill: 8,  label: 'laag',    color: '#e87ab0' },
        ],
        symptoms: ['Gevoelige borsten', 'Opgeblazen gevoel', 'Fysieke vermoeidheid', 'Cravings', 'Stemmingswisselingen', 'Constipatie'],
        prevalence: { 'Gevoelige borsten': 70, 'Opgeblazen gevoel': 65, 'Fysieke vermoeidheid': 60, 'Cravings': 55, 'Stemmingswisselingen': 45, 'Constipatie': 25 },
        sport:   { score: 3, tip: 'Technische training, stabiliteitswerk, duurlopen.' },
        sociaal: { score: 3, tip: 'Diepere gesprekken, vertrouwde kring.' },
        mentaal: { score: 3, tip: 'Geen nieuwe grote toezeggingen. Die plannen van vorige week: schrap wat nu al te veel voelt.' },
        denkvermogen: { score: 3, tip: 'Denken wordt analytischer en detail-gerichter. Goed voor plannen uitwerken, administratie en afmaken.' },
        plannen: 'Je bent analytisch sterk maar hebt minder behoefte aan de spotlight. Goed moment voor detail-werk, administratie en het afronden van lopende projecten. Start niets groots nieuws.',
    },
    {
        range: [21, 35], name: 'Late luteale fase', days: 'Dag 21–28', color: '#2A68A8',
        description: 'Progesteron en oestradiol dalen scherp. Die daling veroorzaakt PMS-klachten en kondigt de volgende menstruatie aan. De dalende oestrogeenspiegel verlaagt ook de serotonineproductie, wat de stemming drukt en de trek in koolhydraten en suiker (zoals chocola) aanwakkert: die geven serotonine tijdelijk een boost. FSH begint al licht te stijgen als voorbereiding op de volgende cyclus.',
        hormones: [
            { name: 'Oestradiol',   fill: 42, label: 'dalend',           color: '#e8d060' },
            { name: 'Progesteron', fill: 85, label: 'flink dalend',           color: '#4db8c8' },
            { name: 'FSH',         fill: 26, label: 'licht stijgend',   color: '#7ab55c' },
            { name: 'LH',          fill: 8,  label: 'laag',   color: '#e87ab0' },
        ],
        symptoms: ['Prikkelbaarheid', 'Stemmingswisselingen', 'Fysieke vermoeidheid', 'Somberheid', 'Opgeblazen gevoel', 'Gevoelige borsten', 'Cravings', 'Angst', 'Hoofdpijn', 'Slaapproblemen', 'Concentratieproblemen', 'Mentale vermoeidheid', 'Onrust', 'Onzekerheid', 'Piekeren', 'Constipatie'],
        prevalence: { 'Prikkelbaarheid': 95, 'Stemmingswisselingen': 93, 'Fysieke vermoeidheid': 91, 'Somberheid': 82, 'Opgeblazen gevoel': 74, 'Gevoelige borsten': 73, 'Angst': 65, 'Cravings': 62, 'Hoofdpijn': 60, 'Slaapproblemen': 45, 'Concentratieproblemen': 45, 'Mentale vermoeidheid': 40, 'Onrust': 35, 'Onzekerheid': 30, 'Piekeren': 25, 'Constipatie': 20 },
        sport:   { score: 2, tip: 'Wandelen, yoga, stretching.' },
        sociaal: { score: 2, tip: 'Kleine, vertrouwde kring. Grote verplichtingen vermijden.' },
        mentaal: { score: 2, tip: 'Zelfkritiek en piekeren zijn hormoongestuurd. Neem ze niet serieus. Geen grote beslissingen over werk, relaties of jezelf.' },
        denkvermogen: { score: 2, tip: 'Concentratie en focus nemen af. Houd het bij routinetaken, opruimen en afronden. Nieuwe complexe taken kosten onevenredig veel moeite.' },
        plannen: 'Energie en stemming dalen. Gebruik deze tijd voor afronden en opruimen, niet voor opstarten. Houd sociale afspraken klein en vertrouwd. Zet chocola op je boodschappenlijstje.',
    },
];
